apiVersion: v1
kind: Secret
metadata:
  name: porter-config
  namespace:  {{ .Release.Namespace }}
  labels:
    porter: "true"
data:
  config.toml: {{ tpl ( .Files.Get "include/config.toml" ) . | b64enc }}
